### ISSUE TITLE
Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by bennyn** [NiGhTTraX/lerna-ts#10]
I wanted to execute the script in "@nighttrax/bar", so I added "ts-node" to the game and a little start script:

**lerna-ts\packages\bar\package.json**

```
{
  ...
  "scripts": {
    ...
    "start": "ts-node ./src/index.ts",
    ...
  },
  ...
}
```

When executing `npm start` I am getting the following error:

> Error: Cannot find module 'C:\dev\projects\bennyn\lerna-ts\packages\bar\node_modules\@nighttrax\foo\dist\
index'. Please verify that the package.json has a valid "main" entry

The problem exists because the "main" entry in "foo" package points to "dist/index". This file does not exist by default so I have to run "npm run build" in the "foo" package directory first before I can start my script in "bar" package.

Do you have an idea how the monorepo can be linked so that I don't have to compile monorepo dependencies first? 

I could change the "main" entry in "foo" package to "src/index" so it uses the existing TypeScript source code but then I will get intro trouble when publishing this package on npmjs since it will point to TypeScript sources and not to compiled JavaScript code.

**Comment by NiGhTTraX** [comment]
Hey @bennyn! You need to use the [`tsconfig-paths`](https://www.npmjs.com/package/tsconfig-paths) package with `ts-node` so that it can resolve the path aliases from the monorepo. Your script would become

```
{
  "scripts": {
    "start": "ts-node -r tsconfig-paths/register ./src/index.ts",
  },
}

**Comment by bennyn** [comment]
This worked like a charm! Thanks for pointing me to [tsconfig-paths](https://www.npmjs.com/package/tsconfig-paths). ✨
