### ISSUE TITLE
Error in build process

### ISSUE THREAD

**Issue by LaleWolf** [NiGhTTraX/lerna-ts#3]
Hey, thanks for that repo.

I was trying to copy the concept for my project. Sadly I couldnt bring it to build successfully, always got the failure "module not found" when I tried to run the build steps in a package with dependecies to other packages. (eg. @nighttrax/foo' not found in package/bar)

So I just tried to simply download and run this repo. Sadly I am running into few errors. May you understand what I am doing wrong?

![image](https://user-images.githubusercontent.com/2292243/73551104-1a6d6d80-4446-11ea-95fb-18dd928c1b5c.png)

I am using vscode on windows, so I changed nothing but the "clean" task. I changed "rm" command to a "rimraf" command which is globally installed, so I dont think thats a issue.

Thanks.

**Comment by Exeteres** [comment]
Same issue

**Comment by NiGhTTraX** [comment]
There's something fishy going on in that screenshot. This project doesn't depend on `@types/node` so I'm not sure where those are coming from. Are you sure your project is clean?

**Comment by Exeteres** [comment]
I fixed it by setting `target` to `es6`.

**Comment by NiGhTTraX** [comment]
@Exeteres glad to hear you fixed it. The config in this repo is very simple and doesn't include any types for building an ES6 project. It's meant to only highlight the parts you need to support a monorepo.

I'm closing this for now, but @LaleWolf if you're still having trouble feel free to re-open.
