### ISSUE TITLE
Compilation does not work

### ISSUE THREAD

**Issue by leguilv** [NiGhTTraX/lerna-ts#4]
Hey,

Thanks for this insightful example. I've a question though: I checked out the project reference branch, and running npm run build on foo yields this error:

src/index.ts:1:27 - error TS2307: Cannot find module '@nighttrax/foo'.

Any idea ?

**Comment by NiGhTTraX** [comment]
Did you run the `npm run bootstrap` script? That's needed so that `lerna` creates the symlinks between packages in `node_modules`.

**Comment by leguilv** [comment]
That's the part I missed indeed :) I wrongly assumed that the "project reference" feature of typescript would take care of that automagically, and realized that if it did, part of what lerna provides would not be required anymore...

I find quite surprising that achieving things that you described in your blog post / repository, i.e. fairly typical situation where you manage multiple packages, some of them being independant, some of them having dependencies on each others, is not provided out of the box by typescript itself, and that we have to rely on such complex setup to get a decent development environment.

Thanks anyways :)
