### ISSUE TITLE
Referenced TS issue in article

### ISSUE THREAD

**Issue by geoff-harper** [NiGhTTraX/lerna-ts#6]
Thanks for the article. It looks like the [issue you reference in the article](https://github.com/microsoft/TypeScript/issues/25376) has seen some progress. Does this impact your solution at all?

**Comment by NiGhTTraX** [comment]
Hey. @geoff-harper. I'm subscribed to that issue and I don't see anything that looks like an official solution right now. The last few updates mention some shell scripts that extract information from yarn workspace, but they're dependent on yarn and you would need to run them every time the monorepo structure changes (the frequency of which depends on the project).
