### ISSUE TITLE
Thoughts on making this repo a template?

### ISSUE THREAD

**Issue by PaulRBerg** [NiGhTTraX/lerna-ts#8]
GitHub has recently introduced the templates feature:

<img width="631" alt="Capture d’écran 2020-06-03 à 12 25 27" src="https://user-images.githubusercontent.com/8782666/83619999-5ac82e00-a595-11ea-8ddb-604effa7a9e7.png">

This repository and its [accompanying article](https://medium.com/@pelotom/nice-article-thanks-ad49e5c04a8f) are so good that I think they deserve to be a template. I spent long hours debugging my TypeScript configs and reading other two tutorials before stumbling upon yours!

Oh, and if I may, a further idea: rebrand this to "ts-monorepo" or something alike - one doesn't have to use lerna to follow through the setup.

**Comment by NiGhTTraX** [comment]
Thanks for the suggestion @PaulRBerg! The repo is now a template :)

![image](https://user-images.githubusercontent.com/485061/83885484-b5ed5280-a746-11ea-899a-c5c760e4c465.png)

> one doesn't have to use lerna to follow through the setup.

You don't lerna to set up the symlinks, you can use yarn instead, but you do need it to compile the packages in the right order, unless you're using the project references branch.
