### ISSUE TITLE
Testing framework 

### ISSUE THREAD

**Issue by zamirdan** [NiGhTTraX/lerna-ts#9]
Hi,
I think you did a great work here, you really saved me! 
the only thing that I was missing is a testing framework, fortunately it was pretty easy to add Mocha and chai - so easy I was sure it's not going to work, I have already made to many changes to run a pull request but if you want to add it to the project I can help - I am also added nyc to get a code coverage report - (the only issue I have is that it's hard to see failing the tests when running lerna run test- but I think it's an issue with Lerna )

**Comment by NiGhTTraX** [comment]
Hey @zamirdan, with this repo I only intend to provide the basic structure of a monorepo and let others add whatever they want on top. Never say never, but right now I don't want to turn this into a starter kit by including opinionated tools.
